package ascent.gui;

public enum ACTION {
    NONE, QUIT, SELECT, INTERACT, MENU, UP, DOWN, LEFT, RIGHT, LOOK_UP, LOOK_DOWN, LOOK_LEFT, LOOK_RIGHT,
    CHEST_APPLY, CHEST_STORE,
    USE_POTION_0, USE_POTION_1, USE_POTION_2, USE_POTION_3, USE_POTION_4,

    UNEQUIP_WEAPON, UNEQUIP_HEAD, UNEQUIP_CHEST, UNEQUIP_LEGS, UNEQUIP_FEET, UNEQUIP_ARMS
}
