package Ascent.gui;

public enum ACTION {
    NONE, QUIT, SELECT, INTERACT, MENU, UP, DOWN, LEFT, RIGHT, LOOK_UP, LOOK_DOWN, LOOK_LEFT, LOOK_RIGHT,
    CHEST_APPLY, CHEST_STORE,
    USE_POTION_0, USE_POTION_1, USE_POTION_2, USE_POTION_3, USE_POTION_4,
    USE_POTION_5, USE_POTION_6, USE_POTION_7, USE_POTION_8, USE_POTION_9
}
